version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: 'cimg/node:14.15.5'
    steps:
      - checkout
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - './*'

  deploy:
    docker:
      - image: 'cimg/node:14.15.5'
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Deploy BE App
          command: |
            npm run backend:deploy
      - run:
          name: Deploy FE App
          command: |
            npm run frontend:deploy

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
